// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package binance

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComWardCapGoBinanceBinance(in *jlexer.Lexer, out *GetAllAssetsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]struct {
							AssetCode  string `json:"assetCode"`
							LogoUrl    string `json:"logoUrl"`
							AssetDigit int64  `json:"assetDigit"`
							Trading    bool   `json:"trading"`
						}, 0, 1)
					} else {
						out.Data = []struct {
							AssetCode  string `json:"assetCode"`
							LogoUrl    string `json:"logoUrl"`
							AssetDigit int64  `json:"assetDigit"`
							Trading    bool   `json:"trading"`
						}{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						AssetCode  string `json:"assetCode"`
						LogoUrl    string `json:"logoUrl"`
						AssetDigit int64  `json:"assetDigit"`
						Trading    bool   `json:"trading"`
					}
					easyjsonD2b7633eDecode(in, &v1)
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComWardCapGoBinanceBinance(out *jwriter.Writer, in GetAllAssetsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjsonD2b7633eEncode(out, v3)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.Bool(bool(in.Success))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAllAssetsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComWardCapGoBinanceBinance(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAllAssetsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComWardCapGoBinanceBinance(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAllAssetsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComWardCapGoBinanceBinance(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAllAssetsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComWardCapGoBinanceBinance(l, v)
}
func easyjsonD2b7633eDecode(in *jlexer.Lexer, out *struct {
	AssetCode  string `json:"assetCode"`
	LogoUrl    string `json:"logoUrl"`
	AssetDigit int64  `json:"assetDigit"`
	Trading    bool   `json:"trading"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "assetCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AssetCode = string(in.String())
			}
		case "logoUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogoUrl = string(in.String())
			}
		case "assetDigit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AssetDigit = int64(in.Int64())
			}
		case "trading":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Trading = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncode(out *jwriter.Writer, in struct {
	AssetCode  string `json:"assetCode"`
	LogoUrl    string `json:"logoUrl"`
	AssetDigit int64  `json:"assetDigit"`
	Trading    bool   `json:"trading"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"assetCode\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetCode))
	}
	{
		const prefix string = ",\"logoUrl\":"
		out.RawString(prefix)
		out.String(string(in.LogoUrl))
	}
	{
		const prefix string = ",\"assetDigit\":"
		out.RawString(prefix)
		out.Int64(int64(in.AssetDigit))
	}
	{
		const prefix string = ",\"trading\":"
		out.RawString(prefix)
		out.Bool(bool(in.Trading))
	}
	out.RawByte('}')
}
